/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-13 00:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import student.StudentDTO;
import java.util.ArrayList;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1656655828988L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1657175059492L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("student.StudentDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>학생 정보 보기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=CHROME\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>실습용 테마</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/c47106c6a7.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <script src=\"js/ie.js\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 <header>\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <h1><a href=\"#\">HANUL301</a></h1>\r\n");
      out.write("            <ul id=\"gnb\">\r\n");
      out.write("                <li><a href=\"list.st\">JDBC(학생목록조회)</a></li>\r\n");
      out.write("                <li><a href=\"list.cu\">고객관리(Mybatis)</a></li>\r\n");
      out.write("                <li><a href=\"list.hr\">Mybatis(사원목록조회)과제</a></li>\r\n");
      out.write("                <li><a href=\"list.js\">JSTL사용</a></li>\r\n");
      out.write("                <!--  list.jsp(jstl폴더안에있음)을 연결하세요. -->\r\n");
      out.write("                <li><a href=\"#\">게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("            <ul class=\"util\">\r\n");
      out.write("                <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!-- 학생의 이름  student_no  student_name,  user_id, ,  first_name,  last_name,\r\n");
      out.write("			 -->\r\n");
      out.write("	<h1 style=\"text-align: center;\">학생정보를 보여 줍니다</h1>\r\n");
      out.write("\r\n");
      out.write("	<table class=\"styled-table\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>학생번호</th>\r\n");
      out.write("				<th>학생이름</th>\r\n");
      out.write("				<th>아이디</th>\r\n");
      out.write("				<th>성</th>\r\n");
      out.write("				<th>이름</th>\r\n");
      out.write("				<th>요청</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("			");

		ArrayList<StudentDTO> list =( ArrayList<StudentDTO> ) request.getAttribute("list");
		for(int i = 0 ;  i<list.size(); i ++){
	
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"detail.st?studentno=");
      out.print(list.get(i).getStudent_no() );
      out.write("&user_id=");
      out.print(list.get(i).getUser_id());
      out.write('"');
      out.write('>');
      out.print(list.get(i).getStudent_no() );
      out.write("</a></td>\r\n");
      out.write("				<td><a href=\"detail.st\">");
      out.print(list.get(i).getStudent_name());
      out.write("</a></td>\r\n");
      out.write("				<td>");
      out.print(list.get(i).getUser_id());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(list.get(i).getFirst_name());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(list.get(i).getLast_name());
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				<form  action=\"detail.st\" method=\"get\" >\r\n");
      out.write("					<input type=\"hidden\" name=\"studentno\" value=\"");
      out.print(list.get(i).getStudent_no());
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"user_id\" value=\"");
      out.print(list.get(i).getUser_id());
      out.write("\">\r\n");
      out.write("					<input type=\"submit\" value=\"detail.st로 요청\">\r\n");
      out.write("				</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("            <div class=\"upper\">\r\n");
      out.write("                <h1>한울직업전문학교</h1>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Policy</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Terms</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Family Site</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Sitemap</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"lower\">\r\n");
      out.write("                <address>\r\n");
      out.write("                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, facere.<br>\r\n");
      out.write("                    TEL : 062-111-1234 C.P : 010-1234-5678\r\n");
      out.write("                </address>\r\n");
      out.write("                <p>\r\n");
      out.write("                    2022 Hanul &copy; copyright all right reserved.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
